spring:
  profiles:
    active: key

  application:
    name: stock-lab
  
  # Java 21+ Virtual Threads Activation
  threads:
    virtual:
      enabled: true
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true

  # Redis Configuration (Reactive)
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 100
          max-idle: 50

  # Kafka (Spring Cloud Stream)
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        orders-out-0:
          destination: order-topic
        orders-in-0:
          destination: order-topic
          group: matching-engine-group

server:
  port: 8080
  tomcat:
    # Virtual Threads optimize the worker threads, but we can still tune the acceptor/poller
    threads:
      max: 200 # Virtual threads handle the actual work, so we don't need a massive thread pool here
    mbeanregistry:
      enabled: true

# Monitoring for High-Performance
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
